# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2bf62d4cbf9289f556997e5a28010ce3b11860b58067ba861aaa78314bc964a91b0642559223f5691754b5d5937622787a88f1630995c1160bced2ebd0c39d

test:
  secret_key_base: 9d5a3525f35947accf07f95af6500880a6e7bad0ebb920e99ab215d5c636965d3e16e316ba2410a13b15cf35f08247d8f85502f83aedaaf274b5545fa58970c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
